# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy
future: true               
published: true            

# The language of the webpage ??http://www.lingoes.net/en/translator/langcode.htm
lang: ko

# Change to your timezone ??https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Seoul

# jekyll-seo-tag settings ??https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ??--------------------------

title: 개발일지

tagline: 알고리즘

description: >- # used by seo meta and the atom feed
  고준환의 블로그입니다. 알고리즘 문제 풀이와 개발 관련 글을 공유합니다.  

# Fill in the protocol & hostname for your site.
url: "https://joonk2.github.io"

github:
  username: joonk2 # change to your github username

social:
  name: 怨좎???J.K
  email: with.joonk@gmail.com
  links:
    - https://github.com/joonk2
    - https://www.instagram.com/withjoonk

# Site Verification Settings
webmaster_verifications:
  google: DUBN2uPITlhUv0RJJ1vZFzHoDrj8uiO-yDh1bYdVuxw
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# ??--------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: # fill in your Google Analytics ID
  goatcounter:
    id: # fill in your GoatCounter ID
  umami:
    id: # fill in your Umami ID
    domain: # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token

# Pageviews settings
pageviews:
  provider: # now only supports 'goatcounter'

# Prefer color scheme setting.
theme_mode: light #[light|dark]  

# The CDN endpoint for media resources.
cdn: ""

# the avatar on sidebar, support local or CORS resources
avatar: "/assets/img/headphone.PNG"

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
social_preview_image: # string, local or CORS resources

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  provider: utterances # [disqus | utterances | giscus]
  disqus:
    shortname: # fill with the Disqus shortname.
  utterances:
    repo: joonk2/joonk2.github.io
    issue_term: pathname
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # optional, default to 'pathname'
    strict: # optional, default to '0'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# Self-hosted static assets, optional
assets:
  self_host:
    enabled: # boolean, keep empty means false
    env: # [development | production]

pwa:
  enabled: true # the option for PWA feature (installable)
  cache:
    enabled: true # the option for PWA offline cache
    deny_paths:

paginate: 10

# The base URL of your site
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts: {}
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:year/:month/:day/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
